In [53]:
import numpy as np

### 1

In [54]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


### 2

In [55]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [56]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [57]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [58]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [59]:
a.reshape(12, 1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

### 3

In [60]:
a = a.reshape(12, -1)

(12, 1)

In [12]:
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [13]:
a.reshape(3, -1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
a.reshape(-1, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
a.reshape(-1, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

### 4

Да, т.к. ```a.ndim``` такого массива возвращает размерность 1.

### 5

In [22]:
a = np.random.randn(3, 4)
a2 = a.reshape(1, -1)
a.size == a2.size

True

### 6

In [ ]:
a = np.arange(20, 0, -2)

### 7

In [61]:
b = np.arange(20, 1, -2)
b = b.reshape(1, 10)
a.shape == b.shape

False

### 8

In [75]:
a = np.zeros((2, 3))
b = np.ones((3, 2))
c = np.vstack((a, b.T))

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 9

In [91]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
print(B.size)
d = np.linalg.det(B)
print(d != 0)

16
False


### 10

In [97]:
np.random.seed(42)

### 11

In [101]:
c = np.random.randint(0, 16, 16)

[ 9  5 12 11  8  0 10 10 14  9 15 11 11 15 14 13]


### 12

In [103]:
C = c.reshape(4, 4)

In [104]:
D = B + C * 10

[[ 95  64 143 142]
 [ 94  50 186 222]
 [163 176 299 322]
 [142 272 352 432]]


In [107]:
D_det = np.linalg.det(D)
D_rank = np.linalg.matrix_rank(D)
D_inv = np.linalg.inv(D)

[[ 0.20411345 -0.01299994 -0.15029082  0.05161   ]
 [ 0.0309618  -0.01359357 -0.02117587  0.01259219]
 [-0.29589854  0.01036158  0.24635726 -0.09168915]
 [ 0.1545152   0.00438928 -0.13800144  0.05213168]]


### 13

In [119]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
print(D_inv)

[[1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [1. 1. 0. 1.]]


In [153]:
E = np.where(D_inv == 1, B, C)
print(E)

[[  5   5  12  32]
 [ 14   0  10 122]
 [ 14  86 149  11]
 [ 32 122  14 302]]
